export enum SubCategory {
  EXTRAORAL = 'EXTRAORAL',
  INTRAORAL = 'INTRAORAL',
  THREEDSCAN = 'THREEDSCAN',
  PLAN_VIDEOS = 'PLAN_VIDEOS',
  CUSTOMER_PLAN = 'CUSTOMER_PLAN',
  MODEL_PDF = 'MODEL_PDF',
  PRESCRIPTION_PATH_PDF = 'PRESCRIPTION_PATH_PDF',
  GNG = 'GNG',
  IPR_SHEET_LAYER_1 = 'IPR_SHEET_LAYER_1',
  IPR_SHEET_LAYER_2 = 'IPR_SHEET_LAYER_2',
  SYSTEM_SHEET_PATH = 'SYSTEM_SHEET_PATH',
  MONITORING_IMAGES = 'MONITORING_IMAGES',
}
